### ISSUE TITLE
Since Python.NET 3.0 int can not be converted to Enum implicitly

### ISSUE THREAD

**Issue by Notnagel** [Hugovdberg/PIconnect#630] opened 2022-01-21 10:55 UTC
Bug report
==========

When defining a time or timerange using `points.recorded_value('-5m')` I get the error 
`Python.Runtime.PythonException: since Python.NET 3.0 int can not be converted to Enum implicitly. Use Enum(int_value)` or token was not expected in string
-----------

I can get current value of points with no problem, so I think this is related to the way timestamps are created/processed.
From reading here: [stackoverflow](https://stackoverflow.com/questions/65805093/pythonnet-why-are-net-enums-type-casted-to-int) this might re related to pythonnet and python 3.9.

On install the install script failed on me because of pythonnet with the error described here [stackoverflow2](https://stackoverflow.com/questions/67418533/how-to-fix-error-during-pythonnet-installation) and I used the suggested solution of a user to manually install with `
pip install pythonnet==3.0.0a2` which worked. After that install of Piconnect worked. But I think something got messed up and I do not have the knowledge to further track down the issue.

To Reproduce Exact Error
------------
Create venv
using python 3.9
install manually `pip install pythonnet==3.0.0a2`
install Piconnect `pip install PIconnect`

use 
```
import PIconnect as PI
with PI.PIServer() as server:
    points = server.search('LDB1.P*')[10]
    data = points.recorded_value('-5m')
    print(data)
```
![grafik](https://user-images.githubusercontent.com/98157383/150515240-dee1b6b3-4cdb-45b8-8790-ce41061305a7.png)

To Reproduce Reduced Error
------------
I went ahead and created a new venv and installed the pythonnet wheel for my Python 3.9 32bit version. This was the actual solution to the pythonnet install issue unter python 3.9 (see [stackoverflow2](https://stackoverflow.com/questions/67418533/how-to-fix-error-during-pythonnet-installation)).
Piconnect installs with no further issues after that.

Now the error is different.
Good news: .recorded_value works now. This failed before
Bad news: Summary still does not work
```
import PIconnect as PI
from PIconnect.PIConsts import SummaryType

with PI.PIServer() as server:
    points = server.search('LDB1.P*')[10]
    #Works
    data = points.recorded_value('-1h')
    print(data)
    #Fails
    data2 = points.summary('*-14d', '*', SummaryType.MAXIMUM)
    print(data2)
```
Error
```
    return AF.Time.AFTimeRange(start_time, end_time)
System.FormatException: The 'd' token in the string '*-14d' was not expected.
```
![grafik](https://user-images.githubusercontent.com/98157383/150540019-1da87a10-7868-4ba2-b8d2-263978448e58.png)

System
------

-   OS: Windows
-   Python version: 3.9.6
-   PIconnect version: latest

**Comment by Hugovdberg** [comment] 2022-01-29 13:48
There was some discussion about it recently: https://github.com/Hugovdberg/PIconnect/discussions/628 but I haven't yet had the time to do the explicit casts to the .NET Enums. Why your summary isn't working using pythonnet 2.5 and python 3.9 I don't know, I cannot reproduce that, which version of the SDK is installed on your system? It appears that message comes from the SDK itself and not PIconnect or Pythonnet.

**Comment by Notnagel** [comment] 2022-01-31 15:42
Thank you for looking into this. I am on OSIsoft(r) AF SDK Version: 2.9.1.8106. In contrast to #628 recorded_value works and only the point summary fails. When I specify a date range explicitly `points.summary('01.01.2021 10:00', '01.01.2021 11:00', SummaryType.AVERAGE)` it works.

So this is somehow related to the string parsing in time.py in the function to_af_time_range at `return AF.Time.AFTimeRange(start_time, end_time)`

I checked, the type of '*-14h* is str

The debugger throws this message


> The 'h' token in the string '*-14h' was not expected.
   bei OSIsoft.AF.Time.AFTimeSpan.FormatError(String input, String token, Boolean throwErrors, AFTimeSpan& result)
   bei OSIsoft.AF.Time.AFTimeSpan.TryParseImpl(String input, Int32 startlocation, IFormatProvider provider, NumberFormatInfo numberFormat, DateTimeFormatInfo dateTimeFormat, Boolean throwErrors, AFTimeSpan& result)
   bei OSIsoft.AF.Time.AFTime.TryParseImpl(String input, Nullable`1 referenceTime, AFTimeZone timeZone, IFormatProvider provider, Boolean throwErrors, DateTime& result)
   bei OSIsoft.AF.Time.AFTime.TryParseRetryImpl(String parmName, String input, Nullable`1 referenceTime, IFormatProvider provider, Boolean throwErrors, AFTime& result)
   bei OSIsoft.AF.Time.AFTimeRange.TryParseImpl(String startTime, String endTime, AFTime referenceTime, IFormatProvider provider, Boolean throwErrors, AFTime& startAFTime, AFTime& endAFTime)
   bei OSIsoft.AF.Time.AFTimeRange..ctor(String startTime, String endTime)

I have found a potential workaround which I have not verified by calling `return AF.Time.AFTimeRange.Parse(start_time, end_time)`

**Comment by Hugovdberg** [comment] 2022-12-17 12:25
Version 0.10.x solves this issue. It is available on PyPI, and I'm working to getting it updated on conda-forge as well, but that has a few issues due to changes in importing the SDK that is not available on the conda build servers. Closing this issue for now.

**Closed by Hugovdberg** 2022-12-17 12:25 UTC
