### ISSUE TITLE
Attribute returns data as floats

### ISSUE THREAD

**Issue by vadtam** [Hugovdberg/PIconnect#490] opened 2019-08-21 13:59 UTC
**Bug report**

**Description**
PIconnect.PIAF.PIAFAttribute object returns data as floats.

**To Reproduce**
```
with PI.PIAFDatabase(server=servers[0],
                     database="Test") as database:
    element = database.descendant(
        r'Europe\A\B')
    attribute = element.attributes['DD']
    print(type(attribute))
    data = attribute.recorded_values('*-5mo', '*')
    for i in range(10):
        print(type(data[i]))
        print(data[i])
```

**Expected behavior**
I expect the data to be of "datetime, float" pairs. But it is only floats. How to get its timestamps?

**System**
-   OS: Windows
-   Python version: Python 3.7.4.
-   PIconnect version: 0.7.1.

**Comment by Hugovdberg** [comment] 2019-08-21 14:09
The `recorded_values` method returns a [`pandas.Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) of the data, where the timestamps of the events are the index of the series. 

The way you retrieve values from the series returns only the data at that location, but not its index. More information on getting subsets of `pandas` objects can be found on this page: [Indexing and selecting data](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html). If you would like to see the first 10 items of the data you could do this:

```python
with PI.PIAFDatabase(server=servers[0],
                     database="Test") as database:
    element = database.descendant(
        r'Europe\A\B')
    attribute = element.attributes['DD']
    print(type(attribute))
    data = attribute.recorded_values('*-5mo', '*')
    print(data.head(10))
```

This is therefore not a bug in `PIconnect`, and I will close the issue. Feel free to comment if you think the way `PIconnect` returns the data is actually wrong.

**Closed by Hugovdberg** 2019-08-21 14:09 UTC

**Comment by vadtam** [comment] 2019-08-22 06:17
subset = data.head(10) is of type <class 'PIconnect.PIData.PISeries'>
cmd_output is as follows:
2017-01-12 15:04:47+01:00    204.395
2017-01-13 15:04:48+01:00    204.395
Name: Rate, dtype: object

How to convert them to (datetime, float) pairs? I tried several solutions from the internet, but it fails.

**Comment by Hugovdberg** [comment] 2019-08-22 08:45
This should work: 

```python
list(zip(data.index, data))
```

See this StackOverflow question: https://stackoverflow.com/a/38468711/4398595
